### ISSUE TITLE
Table of Contents is broken

### ISSUE THREAD

**Issue by matthewfeickert** [matthewfeickert/Dedman-Thesis-Latex-Template#44]
The table of contents is not being generated properly.

**Comment by matthewfeickert** [comment]
@danjardin have you noticed this as well?

@egodat @Alkusoittow you would have had to fix this in your theses. Can you advise?

**Comment by danjardin** [comment]
I don't know what you mean by "broken", but my TOC looks perfectly fine. This even includes the Preface because having a Chapter 0 could mess with some things but it seems to handle that just fine.

As a reference point for you, I haven't touched my thesis since Jan 21 and I believe the template was up to date at that time.

**Comment by egodat** [comment]
I don't recall having any issue with this. I believe I made @matthewfeickert a collaborator on my dissertation repo so if you wanted to run a diff on a specific file or something, you could. I took a peek and didn't see anything indicating I made major modifications to the .sty file.

What do you mean by broken?

**Comment by matthewfeickert** [comment]
> I don't know what you mean by "broken", but my TOC looks perfectly fine.

@danjardin Thanks, that's very helpful feedback. Can you let me know the output of the following command when you run it from the top level of your thesis git repo?

```
git submodule status
```

> I don't recall having any issue with this.

@egodat This is also helpful feedback. What I mean by broken is that the TOC in the [thesis template](https://www.physics.smu.edu/mfeickert/dedman-thesis-latex-template/template.pdf) currently looks like this

![toc_blank](https://user-images.githubusercontent.com/5142394/52510340-389ce680-2bc1-11e9-9604-76460cf201c3.png)

with the (working :+1:) list of tables and list of figures on the following pages.

**Comment by matthewfeickert** [comment]
@danjardin @egodat 

Some quick debugging shows that things work at

```
git submodule status 
+15d2e53353b71b8bd178e85d575cb9f52cdcffb7 Dedman-Thesis-Latex-Template (v0.1.0-6-g15d2e53)
```

and so the regression was introduced in PR #42. I'll start working on fixing this.

@danjardin You weren't planning on updating your thesis anytime soon, but definitely don't so so until this Issue is closed.

**Comment by Alkusoittow** [comment]
Glad you at least found a starting point. Sorry I wasn’t any help! (It worked ok for me)



On Feb 8, 2019, at 11:59 PM, Matthew Feickert <notifications@github.com<mailto:notifications@github.com>> wrote:


@danjardin<https://github.com/danjardin> @egodat<https://github.com/egodat>

Some quick debugging shows that things work at

git submodule status
+15d2e53353b71b8bd178e85d575cb9f52cdcffb7 Dedman-Thesis-Latex-Template (v0.1.0-6-g15d2e53)


and so the regression was introduced in PR #42<https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/pull/42>. I'll start working on fixing this.

@danjardin<https://github.com/danjardin> You weren't planning on updating your thesis anytime soon, but definitely don't so so until this Issue is closed.

**Comment by matthewfeickert** [comment]
@Alkusoittow No worries, this was my bad that I didn't properly check to make sure that adding in a glossary wouldn't mess with any of the house of cards things that the template is doing. So the TOC was building fine until I came along and tried to "improve" things. :/

**Comment by matthewfeickert** [comment]
The good news (for me) is that this might be easy to fix, as simple commenting out the `\begin{thesis}` and `\end{thesis}` lines are able to restore the TOC. So I can at least assume that the issue is regulated to how the `thesis` environment is affecting the TOC generation.

**Comment by matthewfeickert** [comment]
@danjardin This is patched up now. If you want to update your template before you submit your thesis so you can add a glossary let me know and I can help if you have any questions.

**Comment by danjardin** [comment]
I don't see an immediate need for a glossary, but will this cause any problems if I try to update the template for some other reason in the future?

**Comment by matthewfeickert** [comment]
@danjardin I don't think so, given that the only changes to existing files under the template's control were [minor additions](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/pull/42/files#diff-51515fec169b5bf2123a8ba49dde6c3c).

However, you can always check this by cloning your thesis into some temporary directory, running the installer and then seeing if you get any errors.

**Comment by matthewfeickert** [comment]
@danjardin I just tested this. It doesn't break anything if you **don't** use a glossary so you'll be fine.
