### ISSUE TITLE
List of Figure Captions

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#65]
The dissertation guide says "List captions exactly as they appear in the text, if they are relatively brief. If they are long, stop at the first period or other logical stopping point."

This has the feeling of something that has to be manually managed and would be difficult for latex to handle, but I'll create the issue in case I'm wrong. Captions really shouldn't be more than a few sentences anyway or else the text around the figure needs to have more info.

**Comment by matthewfeickert** [comment]
> "List captions exactly as they appear in the text, if they are relatively brief. If they are long, stop at the first period or other logical stopping point."

:expressionless: Here I feel like the guidelines are being designed by people who have never actually done this before. Either that or people who have seen horrors so unspeakable in theses that they need to guard against the extremes. 

> Captions really shouldn't be more than a few sentences anyway or else the text around the figure needs to have more info.

Exactly. 

I'm genuinely glad that you opened this, but since I am in agreement with you I am going to close it as I don't think there is anything for us to do beyond encourage people to be good writers.

**Comment by danjardin** [comment]
> people who have seen horrors so unspeakable in theses

I think this highlights the point that the template can only do so much, hence the multiple rounds of format checks. To anyone writing a whole chapter in your captions... good luck. And even more luck to the reviewers!
